version: '3.8'
services:
  gastro-manager:
    image: ${CONTAINER_IMAGE}
    container_name: gastro-manager
    build: 
      context: ../
    ports:  
    - "8080:9000"
    networks:
    - network_local_server
networks:
  network_local_server:
    external: true
